# Generated by Django 5.0.7 on 2024-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='recipes_image')),
                ('name', models.CharField(max_length=400)),
                ('Category', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('process', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
